#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

getPlatform(){
    if grep -Eqii "Manjaro" /etc/issue || grep -Eq "Manjaro" /etc/*-release; then
        PLATFORM='Manjaro'
    elif grep -Eqii "Ubuntu" /etc/issue || grep -Eq "Ubuntu" /etc/*-release; then
        PLATFORM='Ubuntu'
    elif grep -Eqii "Arch" /etc/issue || grep -Eq "Arch" /etc/*-release; then
        PLATFORM='Arch'
    else
        PLATFORM='Unkown'
        return 1 # failed to detect
    fi
    echo $PLATFORM 
    return 0 # succeed in getting platform
}

# install script
UNAME=$(uname | tr "[:upper:]" "[:lower:]")
if [ "$UNAME" == "linux" ]; then
    PLATFORM=$(getPlatform) 
    echo Platform is: $PLATFORM
    if [ "$PLATFORM" == "Ubuntu" ]; then
        bash ./scripts/ubuntu.sh
    elif [ "$PLATFORM" == "Manjaro" ]; then
        bash ./scripts/manjaro.sh
    elif [ "$PLATFORM" == "Arch" ]; then
        bash ./scripts/arch.sh
    else
        echo "INSTALL SCRIPT FAIL"
    fi
fi

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
